"""fix_medication_columns

Revision ID: 6724fc79eba7
Revises: 8985073cb3d1
Create Date: 2026-06-23 13:24:44.371626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6724fc79eba7'
down_revision: Union[str, None] = '8985073cb3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('medications', sa.Column('times_per_day', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('medications', sa.Column('scheduled_times', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.add_column('medications', sa.Column('use_smart_box', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('medications', 'dosage',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('medications', 'end_date')
    op.drop_column('medications', 'enable_led')
    op.drop_column('medications', 'time_slots')
    op.drop_column('medications', 'enable_buzzer')
    op.drop_column('medications', 'start_date')
    op.drop_column('medications', 'frequency')
    op.drop_column('medications', 'enable_notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('enable_notification', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('enable_buzzer', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('time_slots', postgresql.ARRAY(postgresql.TIME()), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('enable_led', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('medications', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('medications', 'dosage',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('medications', 'use_smart_box')
    op.drop_column('medications', 'scheduled_times')
    op.drop_column('medications', 'times_per_day')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
